Improve installation and fix GEDIvector issue
gbelouze/geefetch pull request #13
Opened 2024-09-30 08:31 UTC by purnelldj

- Fixed error when instantiating GEDIvector class by removing '@abstractmethod' decorator from SatelliteABC
- Added pyarrow as a dependency in pyproject.toml (necessary for Parquet files)
- Suggested installation with less detailed environment.yaml file - change if you wish

2024-09-30 10:43 UTC, gbelouze commented
`get_time_series` should be an abstract method. The fact that it prevented `Gedi_vector` from being instantiated is a feature - the roll of abstract method being to make sure that the children class provide an implementation of certain methods. I added a dummy implementation in the Gedi_vector class.

2024-09-30 10:51 UTC, gbelouze requested changes
Thanks for fixing the conda file. I was misunderstandingly using it as a reference point for a working installation (such as `requirements.txt` files usually are), but it makes more sense for it to be the conda equivalent of the dependencies field in the `pyproject.toml` file.
I'm in favor of removing the version majoration when not needed - but it can be merged otherwise :)

2024-09-30 10:51 UTC, gbelouze commented on environment.yml
Still not a fan of adding version majoration by default. If all packages did this, it'd be mostly impossible to interop packages. Is it standard in the conda packaging norms ? I've never seen this for pyproject.toml files for instance.

2024-09-30 11:07 UTC, purnelldj commented on environment.yml
I don't know what the best solution is. I think the example we just ran into of incompatibility between geefetch and chill is a good argument against having the version numbers for dependencies. However, some of the constraints are necessary, e.g., GDAL needs to be sufficiently old to avoid issues when installing PyTorch.

If you value having geefetch compatible with chill then the best solution would be to set "gdal >=3.7, <3.8" in this environment.yml file. You could remove all the other version constraints (also for chill) and I believe that both packages would install fine and be compatible.

2024-09-30 11:11 UTC, purnelldj commented on environment.yml
Could change to just lower bounds on all packages aside from GDAL?

2024-09-30 11:15 UTC, gbelouze commented on environment.yml
When there is a legitimate need for upper bound as you mention for interop with pytorch - then of course I'm fine with them. However I don't think this necessary for geefetch (even if we want it to work with chill). We can just have the requirements `gdal >= 3.7` here and let conda do dependency resolution for users who want both `geefetch` and `chill`. Wdyt ?

2024-09-30 11:18 UTC, purnelldj commented on environment.yml
Yes sounds good to me, seems like the best fix!

2024-10-01 09:22 UTC, purnelldj commented
I think this is ready to be merged - can keep the pyproject.toml file how you had it with the lower bound for numpy. I was able to have both chill and geefetch installed locally in the same environment with these changes

2024-10-01 09:57 UTC, merged